name: Validate Pull Request

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  validate:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Install dependencies
      run: npm install -g ajv-cli

    - name: Validate JSON files
      run: ajv validate --spec=draft2020 -s tea.schema.json -d "!(tea.schema).json"